spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
    password: postgres
  application:
    name: customer
server:
  port: 9091

management:
  endpoint:
    routes:
      enabled: true
    web:
      exposed:
        included: *